name: go_todo
description: 'GO-TODO Frontend app.'
version: 0.2.2
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.4
  flutter: '3.32.5'

# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. To see which
# dependencies have newer versions available, run `flutter pub outdated`.
dependencies:
  dart_jsonwebtoken: ^3.2.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^3.0.0-dev.17
  http: ^1.4.0
  logging: ^1.3.0
  riverpod_annotation: ^3.0.0-dev.17
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The lint set provided by the package is activated in the
  # `analysis_options.yaml`.
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.0-dev.17
  build_runner: ^2.5.4
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0-dev.17

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
